version: "3.5"

services:
  api:
    container_name: fireside_api
    stdin_open: true
    build:
      dockerfile: ./docker/test/Dockerfile
    depends_on:
      - testing_db
    profiles: ['api', 'backend']
    volumes:
      - ./api:/app
      - /app/node_modules
  discord:
    container_name: fireside_discord
    stdin_open: true
    build:
      dockerfile: ./docker/test/Dockerfile
    depends_on:
      - testing_db
      - api
    volumes:
      - ./discord:/app
      - /app/node_modules
    profiles: ['discord', 'backend']
  testing_db:
    container_name: fireside_testing_db
    image: 'postgres:14.5'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5678:5432
    volumes:
      - ./postgres_testing_data:/var/lib/postgresql/data