version: "3.5"

services:
  api:
    container_name: fireside_api
    stdin_open: true
    build:
      dockerfile: ./docker/test/Dockerfile
    depends_on:
      - testing_db
    volumes:
      - ./api:/app
      - /app/node_modules
  testing_db:
    container_name: fireside_testing_db
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5678:5432
    volumes:
      - ./postgres_testing_data:/var/lib/postgresql/data