export const GET_GUILDS_REQUEST = "GET_GUILDS_REQUEST";
export const GET_GUILDS_SUCCESS = "GET_GUILDS_SUCCESS";
export const GET_GUILDS_FAILURE = "GET_GUILDS_FAILURE";

export const UPDATE_MANAGED_GUILD = "UPDATE_MANAGED_GUILD";